do
msgbox("Ooh ooh"),0,("Never Gonna Give You Up")
msgbox("We're no strangers to love"),0,("Never Gonna Give You Up")
msgbox("You know the rules and so do I"),0,("Never Gonna Give You Up")
msgbox("A full commitment's what I'm thinking of"),0,("Never Gonna Give You Up")
msgbox("You wouldn't get this from any other guy"),0,("Never Gonna Give You Up")
msgbox("I just wanna tell you how I'm feeling"),0,("Never Gonna Give You Up")
msgbox("Gotta make you understand"),0,("Never Gonna Give You Up")
msgbox("Never gonna give you up"),0,("Never Gonna Give You Up")
msgbox("Never gonna let you down"),0,("Never Gonna Give You Up")
msgbox("Never gonna run around and desert you"),0,("Never Gonna Give You Up")
msgbox("Never gonna make you cry"),0,("Never Gonna Give You Up")
msgbox("Never gonna say goodbye"),0,("Never Gonna Give You Up")
msgbox("Never gonna tell a lie and hurt you"),0,("Never Gonna Give You Up")
msgbox("We've known each other for so long"),0,("Never Gonna Give You Up")
msgbox("Your heart's been aching but"),0,("Never Gonna Give You Up")
msgbox("You're too shy to say it"),0,("Never Gonna Give You Up")
msgbox("Inside we both know what's been going on"),0,("Never Gonna Give You Up")
msgbox("We know the game and we're gonna play it"),0,("Never Gonna Give You Up")
msgbox("And if you ask me how I'm feeling"),0,("Never Gonna Give You Up")
msgbox("Don't tell me you're too blind to see"),0,("Never Gonna Give You Up")
msgbox("Never gonna give you up"),0,("Never Gonna Give You Up")
msgbox("Never gonna let you down"),0,("Never Gonna Give You Up")
msgbox("Never gonna run around and desert you"),0,("Never Gonna Give You Up")
msgbox("Never gonna make you cry"),0,("Never Gonna Give You Up")
msgbox("Never gonna say goodbye"),0,("Never Gonna Give You Up")
msgbox("Never gonna tell a lie and hurt you"),0,("Never Gonna Give You Up")
msgbox("Never gonna give you up"),0,("Never Gonna Give You Up")
msgbox("Never gonna let you down"),0,("Never Gonna Give You Up")
msgbox("Never gonna run around and desert you"),0,("Never Gonna Give You Up")
msgbox("Never gonna make you cry"),0,("Never Gonna Give You Up")
msgbox("Never gonna say goodbye"),0,("Never Gonna Give You Up")
loop